# config/config.yaml
data:
  tickers:
    - PETR4.SA
    - VALE3.SA
    - ITUB4.SA
    - AAPL
    - MSFT
    - BTC-USD
  start: "2018-01-01"
  end: "2024-12-31"
  interval: "1d"

split:
  train_start: "2018-01-01"
  test_start: "2022-01-01"
  test_end: "2024-12-31"
  retrain_frequency: "M"

models:
  arima:
    order: [2, 1, 2]
  garch:
    p: 1
    q: 1
    dist: "normal"
  rf:
    n_estimators: 200
    max_depth: 8
    random_state: 42
  logit:
    C: 1.0
    penalty: "l2"
    max_iter: 300

ensemble:
  weights:
    arima: 0.25
    garch: 0.15
    rf: 0.35
    logit: 0.25
  thresholds:
    buy: 0.60
    sell: 0.40

risk:
  atr_window: 14
  atr_multiplier: 2.0
  target_ratio: 2.5
  risk_per_trade_pct: 0.01
  use_kelly: true
  kelly_fraction: 0.25
  kelly_cap: 0.05
  max_hold_days: 30

backtest:
  initial_equity: 100000
  slippage_bps: 3
  commission_bps: 2
